name: chateo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  avatars: ^3.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_database: ^10.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  fluttertoast: ^8.2.4
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
